theme = "academic"
baseURL = "https://thomasvanhoey.com/"
languageCode = "en-us"
title = "Thomas Van Hoey | Sinologica"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
