---
title: "CV"
author: "Thomas Van Hoey 司馬智"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  pdf_document:
    latex_engine: xelatex
    template: template_thomas.tex
  html_document:
    df_print: paged
CJKmainfont: Noto Sans CJK TC
sansfont: Impact
mainfont: Noto Serif
geometry: margin=1in
jobtitle: Postdoctoral assistant, Department of Linguistics
affiliation: KU Leuven
addressuni: Blijde Inkomststraat 21, 3000 Leuven
fontawesome: yes
academicons: yes
email: thomas_van_hoey@outlook.com
# email2: thomasvh@hku.hk
github: github.com/simazhi
phone: +32 472 32 43 00
web: thomasvanhoey.com
orcid: 0000-0002-5226-9752
updated: yes
keywords: R Markdown, academic CV, template
fontsize: 12pt
linkcolor: blue
urlcolor: blue
keep_tex: yes
---

<!-- # Biography 

qulificiation,
outstanding teaching
reserch
community engagement
3 paragraphs of prose

-->
\thispagestyle{empty}
# Research interests

Ideophones, onomatopoeia, mimetics; Cognitive Linguistics; lexical semantics; Cognitive Grammar;  
historical linguistics; Chinese (in all its variants)

# Employment

**Postdoctoral assistant**, KU Leuven \hfill 2022-present

**Postdoctoral fellow**, The University of Hong Kong \hfill 2021-2022 
<!-- \newline -->
<!-- (PI [Youngah Do, Ph.D](http://hub.hku.hk/cris/rp/rp02160), Co-Is [Mark Dingemanse, Ph.D](https://markdingemanse.net/) \hfill Hong Kong \newline -->
<!-- \mbox{} \qquad{} -->
<!-- & Arthur Lewis Thompson, Ph.D; GRF 17603120) -->


# Education

**PhD Linguistics** *(A+)*, National Taiwan University: Graduate Institute of Linguistics \hfill 2015-2020 \newline
Dissertation: *Prototypicality and salience of Chinese ideophones: * \hfill Taipei, Taiwan \newline
\mbox{} \qquad{}\qquad{}\qquad{} *A cognitive and corpus linguistics approach* \newline
<!-- doi: 10.6342/NTU202003830 \newline -->
Advisor: [Lu Chiarung 呂佳蓉, Ph.D](chiarung.blog.ntu.edu.tw) 

**MA Linguistics** *(magna cum laude)*, KU Leuven \hfill 2014-2015  
Thesis: *Ideophones in Middle Chinese:* \hfill Leuven, Belgium \newline 
\mbox{} \qquad{}\qquad{}*A typological study of a Tang dynasty poetic corpus*  
Advisor: [Jean-Christophe Verstraete, Ph.D](https://perswww.kuleuven.be/~u0005010/jcv/) 

**MA Sinology** *(magna cum laude)*, KU Leuven \hfill 2013-2014  
Thesis: *The Guwen yundong 古文运动 (Classical Prose Movement)* \hfill Leuven, Belgium \newline
\mbox{} \qquad{}\qquad{} *during Tang and Song: Ideological as well as Stylistic Innovation?*  
Advisor: [Willy Vande Walle, Ph.D](https://www.kuleuven.be/wieiswie/en/person/00009507)

**Year-long Mandarin Chinese exchange study**, Suzhou University 苏州大学 \hfill 2012-2013 \newline
\mbox{} \hfill Suzhou, China

**BA Sinology** *(cum laude)*, University of Leuven \hfill 2009-2012 \newline
\mbox{} \hfill Leuven, Belgium

# Additional training and education
Summer school: Chinese Digital Humanities. Leiden: Leiden University. \hfill July 2016

Summer school:  Translating Chinese (Summer +10). Taipei: National Taiwan University. \hfill July 2014




# Honours and awards

* \- Editor's choice for Thompson, Van Hoey & Do. *Cognitive Linguistics*. (free open access) \hfill 2021
* \- Financial Assistance Grant for International Students \hfill 2019-2020
* \- Financial Assistance Grant for International Students  \hfill 2018-2019
* \- Research Fellowship for Outstanding International Doctoral Students  \hfill 2015-2018
* \- Scholarship from the Hanban 汉办, for long-term study of Chinese \hfill 2012-2013


# Research






<!-- ## Books -->

## Refereed articles

(@)
**Van Hoey, Thomas**. 2022. The blending of bending: How we engage with the World of *Avatar: The Last Airbender* through memes. Metaphor and Symbol 37(3). 185–207. [doi: 10.1080/10926488.2021.1973868](https://doi.org/10.1080/10926488.2021.1973868)

(@)
Thompson, Arthur Lewis, **Thomas Van Hoey** & Youngah Do. 2021. Articulatory features of phonemes pattern to iconic meanings: Evidence from cross-linguistic ideophones. *Cognitive Linguistics* 32(4). 563-608. \* [doi: 10.1515/cog-2020-0055](https://10.1515/cog-2020-0055)
\*Editor's choice for this issue


(@)
**Van Hoey, Thomas** & Arthur Lewis Thompson. 2020. The Chinese Ideophone Database (CHIDEOD). *Cahiers de Linguistique Asie Orientale* 49(2). 136–167. [doi: 10.1163/19606028-bja10006](https://doi.org/10.1163/19606028-bja10006)

(@)
**Van Hoey, Thomas**. 2018. Does the thunder roll? Mandarin Chinese meteorological expressions and their iconicity. *Cognitive Semantics* 4(2). 230-259. [doi: 10.1163/23526416-00402003](https://doi.org/10.1163/23526416-00402003)

<!-- ## Non-refereed articles -->

<!-- ## Journalism -->

## Book chapters

(@)
**Van Hoey, Thomas**. *forthcoming*. Onomatopoeia in Mandarin Chinese. In Lívia Körtvélyessy & Pavol Štekauer (eds.), Edinburgh Handbook of Onomatopoeia (Handbooks of Linguistics). Mouton de Gruyter. 
(*accepted*, [preprint doi: 10.31219/osf.io/s72mj](https://osf.io/s72mj))


(@)
**Van Hoey, Thomas**. *forthcoming*. A semantic map for ideophones. In Thomas Fuyin Li (ed.) *Handbook of Cognitive Semantics*. Ch. 16. Leiden: Brill. (*accepted*, [preprint doi: 10.31219/osf.io/muhpd](https://osf.io/muhpd/))

(@)
**Van Hoey, Thomas** \& Chiarung Lu. 2019. Lexical variation of ideophones in Chinese classics: Their implications in embodiment and migration. In Janice Fon (ed.), *Dimensions of diffusion and diversity*, 195–226. (Cognitive Linguistics Research 63). Berlin; Boston: De Gruyter Mouton. [doi: 10.1515/9783110610895](https://doi.org/10.1515/9783110610895)

## Publications under review

(@)
Do, Youngah\*, Arthur Lewis Thompson\*, **Thomas Van Hoey**\* & Mark Dingemanse. Iconicity in ideophones: When memory fails, just guess. *under review*  
\* co-first authors
<!-- Cognitive Science -->

(@)
**Van Hoey, Thomas**. ABB, a salient prototype of collocate-ideophone constructions in Mandarin Chinese. *under review*
<!-- Cognitive Linguistics -->

(@)
Do, Youngah, Bingzi Yu & **Thomas Van Hoey**. You can go your own way: Self-directed and active phonological learning. *under review*
<!-- Language and Cognition -->

(@)
Do, Youngah, Xiaoyu Yu, **Thomas Van Hoey**, Baichen Du & Lihui Tan. Adults intuitively prefer learning regular novel phonological patterns: A tale of two planets. 
<!-- Nature Scientific Reports -->


## Publications in preparation

(@)
**Thomas Van Hoey**, Xiaoyu Yu & Youngah Do. Converging evidence: ABB constructions in Mandarin analyzed in the corpus and rated in the experiment.

(@)
**Van Hoey, Thomas**\*, Arthur Lewis Thompson\*, Aaron Wing Cheung Chik, Youngah Do & Mark Dingemanse. Teasing apart sound, meaning and gesture of ideophones in a transmission and iterated learning paradigm.  
\* co-first authors


(@)
**Van Hoey, Thomas** & Tungle Pan. The iconicity of ABB across Sinitic languages.

## Theses

(@)
PhD thesis Linguistics (grade: A+) \hfill 2020 \newline
*Prototypicality and salience of Chinese ideophones: A cognitive and corpus linguistics approach* \newline
漢語擬聲(態)詞的原型與顯著特徵：以認知與語料庫語言學方法探討

(@)
MA thesis Linguistics (grade: 17.4/20)\hfill 2015 \newline
*Ideophones in Middle Chinese: A typological study of a Tang dynasty poetic corpus* 

<!-- >Based on a corpus of Middle Chinese poetry, I identified a set of mimetic words in Middle Chinese. I worked on an analysis of their morphological, phonological, syntactic and semantic properties, against a typological background. -->

(@)
MA thesis Sinology (grade: 18.6/20)\hfill 2014 \newline
*The *Guwen yundong 古文运动 *(Classical Prose Movement) during Tang and Song:* \newline
*Ideological as well as Stylistic Innovation?*

<!-- >Using quantitative analyses (dendrograms, PCA, cluster analysis), I verified which authors were stylistically part of the Classical Prose Movement. This movement promoted an older style (used some four centuries or more earlier), condemning the formal style of the contemporary popular parallel prose. Unlike theoretical research hitherto suggested, my analysis shows that only a few authors formed the core of the movement. The presence of these authors fits nicely into the dominant framework of the emergence of Neo-Confucianism in the Song dynasty (10th-13th cent.). -->

## Resources and data sets

(@)
**Van Hoey, Thomas** & Arthur Lewis Thompson. 2019. The Chinese ideophone database (CHIDEOD). \newline 
CHIDEOD is accessible in .xlsx, .csv, .rds formats (doi: [10.17605/OSF.IO/KPWGF](https://osf.io/kpwgf/)), as well as through a [Shiny app interface](https://simazhi.shinyapps.io/chideod_appversion/).



# Conferences

<!-- ## Keynote addresses -->

## Invited talks

(@)
**Van Hoey, Thomas**. 2022. Articulatory features of phonemes pattern to iconic meanings: Evidence from cross-linguistic ideophones. IcoSem 10. 9 February 2022. Published as Thompson, Van Hoey & Do in *Cognitive Linguistics* (2021). https://youtu.be/UlJpI9FhUmE 

(@)
**Van Hoey, Thomas**. 2019. Defining Chinese ideophones: A family of constructions. International Workshop on Mimetics (Ideophones, Expressives) III: Crucibles of Mimetics. Nagoya: Nanzan University. 3 August 2019. [doi:10.6084/m9.figshare.12651896](https://doi.org/10.6084/m9.figshare.12651896)

(@)
**Van Hoey, Thomas**. 2017. Chinese ideophones in historical corpora: A case study of mental space markers. Workshop on Mimetics II: New approaches to old questions. Nagoya: Nanzan University. 11 November 2017. Funding: MOST-106-2922-I-002-596. [doi:10.6084/m9.figshare.5830341](https://doi.org/10.6084/m9.figshare.5830341)



## Theme sessions 
<!-- ## Conference panels -->

(@)
Dingemanse, Mark, Arie Verhagen, Jonas Nölle & **Thomas Van Hoey**. 2019. Integrating iconicity: Recent work and future directions. ICLC 15 [International Cognitive Linguistics Conference], Nishinomiya: Kwansei Gakuin University. 6-11 August 2019. https://iclc2019.site/. 

## Conference presentations (oral)

(@)
**Van Hoey, Thomas**. Iconicity in the streets, multimodal metaphor in the sheets: Chinese ideophones on social media. 56th Annual Meeting of the Societas Linguistica Europaea (SLE 2023). Athens: National and Kapodistrian University of Athens. 29 August - 1 September 2023.


(@)
**Van Hoey, Thomas**, Matt H. Gardner & Benedikt Szmrecsanyi. Speaking of variation and, uhm, complexity in a corpus of spoken dialogues. 44th conference of the International Computer Archive of Modern and Medieval English (ICAME 44). Vanderbijlpark: North-West University. 17-21 May 2023. 


(@)
**Van Hoey, Thomas**,\* Arthur Lewis Thompson,\* Youngah Do & Mark Dingemanse. 2023. Iconicity in ideophones: When memory fails, just guess.  45th Annual Meeting of the Deutsche Gesellschaft für Sprachwissenschaft. Köln: University of Cologne. 8-9 March 2023. (*Co-first authors) 


(@)
**Van Hoey, Thomas**. 2022. ABB, a salient prototype of collocate-ideophone constructions in Mandarin Chinese. WTI [Workshop on Typology of Ideophones], Toronto: York University & Nagoya: Nagoya University. 24-25 June 2022. [Youtube presentation](https://youtu.be/c6nybV6xnYA)

(@)
Do, Youngah,  Arthur Lewis Thompson, **Thomas Van Hoey**, Aaron Wing Cheung Chik & Mark Dingemanse. 2022. Teasing apart the interplay between gesture, sound and meaning of ideophones through transmission and iterated learning. ILL 13 [International Symposium on Iconicity in Language and Literature], Paris: Sorbonne University. 31 May- 21 June 2022. Funding: GRF 17603120.

(@)
**Van Hoey, Thomas** & Iju Hsu. 2020. Chinese ideophones in advertisements and social media: Motivated by multimodal metaphors. RaAM 13 [Association for Researching and Applying Metaphor] *Virtual*. Hamar: Inland Norway University. 18-21 June 2020. [doi:10.6084/m9.figshare.12651890](https://doi.org/10.6084/m9.figshare.12651890)

(@)
**Van Hoey, Thomas** & Chiarung Lu. 2020. From ideational to interpersonal: A behavioral profile analysis of *qǐlái* 起來 in Modern Mandarin. CLDC 10 [Conference on Language, Discourse, and Cognition]. Taipei: National Taiwan University. 1-2 May 2020. https://sites.google.com/view/cldc10 *(cancelled due to corona virus)*

(@)
**Van Hoey, Thomas** & Chiarung Lu. 2019. Reduplication as a trigger of intersubjectivity: Mandarin Chinese ideophones and reduplication in the CHILDES corpora. ICLC 15 [International Cognitive Linguistics Conference], Nishinomiya: Kwansei Gakuin University. 6-11 August 2019. [doi:10.6084/m9.figshare.12651902](https://doi.org/10.6084/m9.figshare.12651902) 

(@)
**Van Hoey, Thomas**. 2019. Radiant suns, burning fires and brilliant flowers: The onomasiology and radical support of Chinese literary LIGHT ideophones. ICLC 15 [International Cognitive Linguistics Conference], Nishinomiya: Kwansei Gakuin University. 6-11 August 2019. Funding: NTU, College of Liberal Arts. [doi:10.6084/m9.figshare.12652445](https://doi.org/10.6084/m9.figshare.12652445) 

(@)
**Van Hoey, Thomas** & Arthur Lewis Thompson. 2019. Bridging phonology, meaning, and written form across time: Introducing a database of Chinese literary ideophones — CHIDEOD. ILL 12 [International Symposium on Iconicity in Language and Literature], Lund: Lund University. 3-5 May 2019. Funding: MOST-108-2922-I-002-198. [doi:10.6084/m9.figshare.12651899](https://doi.org/10.6084/m9.figshare.12651899)

(@)
**Van Hoey, Thomas** & Chiarung Lu. 2018. All that glitters is not gold: Prototypical semantic change in shiny Literary Chinese ideophones. ICPEAL 17 [International Conference on the Processing of East Asian Languages]-CLDC 9 [Conference on Language, Discourse, and Cognition]. Taipei: National Taiwan University. 19-21 October 2018.  [doi:10.6084/m9.figshare.12652544](https://doi.org/10.6084/m9.figshare.12652544)

(@)
**Van Hoey, Thomas**. 2016. Ideophones in Old Chinese: The case of the *Shijing* 詩經. ISACG [International Symposium on Ancient Chinese Grammar] 9. Berlin: Humboldt University. 29-30 July 2016. [doi:10.6084/m9.figshare.12651875](https://doi.org/10.6084/m9.figshare.12651875)

(@)
**Van Hoey, Thomas**. 2016. A diachronic analysis of ideophones in Chinese. Summer school in Chinese Digital Humanities. Leiden: Leiden University. 6-9 July 2016. [doi:10.6084/m9.figshare.12652508](https://doi.org/10.6084/m9.figshare.12652508)

(@)
**Van Hoey, Thomas** & Chiarung Lu. 2016. The distribution of ideophones in Tang poems: A variationist perspective. CLDC [Conference on Language, Discourse, and Cognition] 8. Taipei: National Taiwan University.13-14 May 2016. [doi:10.6084/m9.figshare.12651824](https://doi.org/10.6084/m9.figshare.12651824)


## Conference presentations (posters)

(@)
**Van Hoey, Thomas**. 2018. The blending of bending: Worldbuilding in *Avatar: The Last Airbender* and *The Legend of Korra*. RaAM [Association for Researching and Applying Metaphor] 12. Hong Kong: Hong Kong Polytechnic University. 27-30 June 2018. Funding: MOST-107-2922-I-002-237. [doi:10.6084/m9.figshare.12652460](https://doi.org/10.6084/m9.figshare.12652460)

(@)
**Van Hoey, Thomas**. 2017. The thunder rolls: Iconicity and ideophones in Chinese meteorological expressions. CLS-MPI Iconicity Focus Group Workshop: Types of Iconicity in Language Use, Development and Processing. Nijmegen: Max Planck Institute for Psycholinguistics. 6-7 July 2017. Funding: NTU, College of Liberal Arts. [doi:10.6084/m9.figshare.12652526](https://doi.org/10.6084/m9.figshare.12652526)

(@)
**Van Hoey, Thomas**. 2016. Ideophones in Premodern Chinese: Revisiting Dingemanse’s implicational hierarchy (poster). Mimetics in Japanese and other languages in the world (日本語と世界諸言語のオノマトペ). Tachikawa: NINJAL. 17-18 December 2016. Funding: MOST-105-2922-I-002-682. [doi:10.6084/m9.figshare.12652514](https://doi.org/10.6084/m9.figshare.12652514)

## Departmental lectures

(@)
**Van Hoey, Thomas**. 2021. Tuples and prototypes of collocate-ideophone constructions like ABB in Manarin Chinese. VLT talks. Hong Kong: University of Hong Kong. 29 June 2021.

(@)
**Van Hoey, Thomas**. 2017. A semantic map for ideophones: From an implicational hierarchy to the spinning top model. Brown Bag Lectures. Taipei: National Taiwan University. 26 April 2017.

## Contributions

(@)
Van de Velde, Freek & Dirk Pijpops, in collaboration with Mathias De Backer, Wendy Feytons, Alek Keersmaekers, Veerle Monserez, **Thomas Van Hoey**, and Marie Vanwingh. 2016. Addressees use Zipf’s law as a cue for semantics. In Seán G. Roberts, Christine Cuskley, Luke McCrohon, Lluís Barceló-Coblijn, Olga Fehér & Tessa Verhoef (eds.), The evolution of language: Proceedings of the 11th international conference (EVOLANGX11). Online at http://evolang.org/neworleans/papers/117.html.


## Tutorials

(@)
**Van Hoey, Thomas**. 2022. R Tutorial for cleaning PsychoPy data. The University of Hong Kong. Delivered for "Laboratory Linguistics" (LING 3006). [youtube](https://youtu.be/7W3_xd7sJ_s) 


(@)
**Van Hoey, Thomas**. 2021. R Tutorial for Linguistics Pioneering Initiative. National Taiwan University. 6 lectures during November 2021. *(soon to be released on YouTube)*

(@)
**Van Hoey, Thomas**. 2019. R bootcamp for lexical semanticists. Introduction to wrangling raw data to formats useable for further analysis using R. Seminar on Language and Culture 語言與文化專題研究.Taipei: National Taiwan University. 5 lectures during November 2019. [blogpost](https://www.thomasvanhoey.com/post/rbootcamp-2019/)

## Broader audiences

(@)
**Van Hoey, Thomas** & CJ Young. 2019. Language, culture, and cognition. Summer training camp for Taiwanese and Hong Kong high school representatives in the International Linguistics Olympiad. Taipei: Academia Sinica. 17 July 2019.

(@)
**Van Hoey, Thomas**. 2018. Austronesian languages. Summer training camp for Taiwanese high school representatives in the International Linguistics Olympiad. Chiayi: National Chungcheng University. 19 July 2018.


# Funding

## Fellowships

- 2019-2020 \qquad NTU, Financial Assistance Grant for International Students
- 2018-2019 \qquad NTU, Financial Assistance Grant for International Students
- 2015-2018 \qquad NTU, Research Fellowship for Outstanding International Doctoral Students
- 2012-2013 \qquad Hanban scholarship

## Travel grants

- 2022 \qquad HKU, RCGAS 202107170056
- 2019 \qquad NTU, College of Liberal Arts
- 2019 \qquad MOST-108-2922-I-002-198
- 2018 \qquad MOST-107-2922-I-002-237
- 2017 \qquad NTU, College of Liberal Arts
- 2016 \qquad MOST-105-2922-I-002-682





# Teaching

- 2022\phantom{-2020} \qquad  Introduction to Cognitive Linguistics (MA) (LING 7011) \hfill HKU
- 2019-2020 \qquad English conversation (BA2) \hfill Tatung University 

# Supervision

- 2022 \qquad Feng, Yuanping \hfill "Analysis of tendency towards usage of different SFPs in Mandarin Chinese"
- 2022 \qquad Liang, Yifan \hfill "Gender terms in Mandarin Chinese: A corpus-based study"

<!-- # Examinations -->

# Service 
<!-- Administration, leadership, management -->

* Sinalumni (alumni association of Sinology students) \hfill 2015-ongoing \newline
management of membership database and coordinating KU Leuven Connect

## Reviewing

* *Canadian Journal of Linguistics / Revue canadienne de linguistique*
* *Cognitive Linguistics*
* *Frontiers*
* *Glossa*
* *Journal of Experimental Psychology:  Learning, Memory, and Cognition*
* *Handbook of Cognitive Semantics*
* *Language and Cognition*
* *Language Sciences*
* *Linguistics Vanguard*
* *Mapping China Journal*
* *PLoS*
* *Review of Cognitive Linguistics*

## Conference organisation

ICPEAL 17 - CLDC 9 \hfill 2018  
*International Conference for the Processing of East Asian Languages* and *Conference on Language, Discourse, and Cognition*
http://homepage.ntu.edu.tw/~gilntu/icpeal2018cldc/ \newline
Role: coordinator of the student committee responsible for organizing the joint conference


<!-- ## Student representation -->

<!-- **Eoos** (student association for the research unit of Area Studies at KU Leuven, Belgium) -->

<!-- - Webmaster \hfill 2014-2015 -->
<!-- - President & Webmaster \hfill 2013-2014 -->
<!-- - Vice President Sinology \hfill 2011-2012 -->
<!-- - Educational representative \hfill 2011-2012 -->
<!-- - Chairman Student Council Faculty of Arts (StRaaL) \hfill 2011-2012 -->

<!-- > Roles: membership of the following bodies: Permanent Educational Commission (POC) of Area Studies, Curriculum Commission (CC) of Linguistics, CC of Sinology, Didactical Commission, Faculty board of the Faculty of Arts, Faculty council of the Faculty of Arts, General student council (LOKO and STURA KU LEUVEN), Student council of the Faculty of Arts (StRaaL) -->

<!-- # Professional development
learning, seminar,
summer schools?
-->




# Consultancies

<!-- Het Taalmuseum tentoonstelling over iconiciteit -->


Premodern Japanese grammar for Sterk, Darryl. 2020. *Indigenous cultural translation: A thick description of Seediq Bale*. New York: Routledge.

<!-- # Media section -->

# Membership

- International Cognitive Linguistics Association
- Researching and Applying Metaphors
- Linguistics Society of Taiwan
- European Association of Chinese Studies


# Previous employment

Research and Teaching Assistant, National Taiwan University \hfill 2019-2020 \newline
*Contemporary online language variation: A case study of Internet public opinion analysis, research assistent, PI  Chiarung Lu* (MOST 108-2410-H-002-059)

Research Assistant, National Taiwan Normal University \hfill 2019-2020  
*Assisting in Formosa-related newspaper project, PI  Ann Heylen*

Research and Teaching Assistant, National Taiwan University \hfill 2016-2019  
*Assisting in courses and research, for Chiarung Lu*

Teaching Assistant, English summer camp at Wesley Girls' High School (Taipei), \hfill 2018  
organized by the Language Training & Testing Center at National Taiwan University

Research Assistant for the Formosan Spoken Corpus, National Taiwan University \hfill 2017-2018  
*Transcribing Isbukun Bunun, PI Li-May Sung*

Dutch translator of Chinese short stories, babel101.com \hfill 2014-2016

Freelance Chinese-Dutch translator and interpreter, Judicial Court of Leuven \hfill 2014-2016

Assistant, East-Asian Library (University of Leuven) \hfill 2014-2015

Freelance translator Dutch-Chinese, Expat Insurances \hfill 2012-2013

# Languages

**Active:** Dutch, English, Chinese, French 

**Passive:** Japanese, German, Premodern Chinese

**Basic knowledge:** Isbukun Bunun (Austronesian)

# Technological knowledge
- Moodle
- Microsoft office (Word, Excel, PowerPoint, Access) and open source variants
- \LaTeX{} (typesetting)
- Database construction and management
- Application deployment with Shiny
- R, Python (statistical research)
- Psychopy3 and Pavlovia
- Experimental design and corpus research
- Regression analysis, cluster analysis, principal components analysis, dendrograms
<!-- - Knowledge of general linguistic theories, (lexical-semantial) Cognitive Linguistics, descriptive and typological linguistics, computational linguistics -->

<!-- # Relevant courses -->
<!-- National Taiwan University:  -->

<!-- > Syntax, Phonology, Lexical Semantics, R Language and Data Science, Linguistic Fieldwork, Logical Analysis of Language, Language and Culture, Corpus Linguistics, Advanced Cognitive Grammar, Cognitive Science, Linguistics in Manga and Animation, Problem-Based Learning Approach to SLA, Manchu -->

<!-- University of Leuven:  -->

<!-- >Language Typology and Universalia, Computational Linguistics, Modern Mandarin Chinese and Classical Chinese (BA and MA courses), Lexicology and Morphology, Pragmatics and Discourse Analysis, Language Documentation and Description, Language Experiment, Historical Linguistics, Comparative Linguistics, Usage-based Linguistics, Introduction to Modern Japanese (2 semesters) -->

# Other awards and certificates
- Intermediate level, Isbukun Bunun Proficiency Test  \hfill 2018
- 1st place at Hackathon Taiwanese Linguistics Olympiad \hfill 2017
- HSK 6 (Chinese Proficiency Test, level 6) \hfill 2013
- HSK 5 (Chinese Proficiency Test, level 5) \hfill 2013
- 3rd place, Chinese calligraphy competiton with hard pen for Belgian university students \hfill 2011
- HSK 3 (Chinese Proficiency Test, level 3) \hfill 2010
- Finalist, HUB (Brussels) Language Competition, French  \hfill 2009
-	Finalist, Olyfran (French language competition)  \hfill 2007

<!-- # Referees -->
<!-- Youngah, Mark, Chiarung, Hsieh, Willy, Standaert, Carine -->

