---
title: The Abralin lectures
author: 'Thomas Van Hoey'
date: '2020-06-18'
slug: the-abralin-lectures
categories:
  - Blog
tags:
  - linguistics
subtitle: ''
summary: ''
authors: []
lastmod: '2020-06-18T00:19:06+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# ~~Love~~ Linguistics in the time of ~~cholera~~ coronavirus. 

In a time where most institutions of most countries (yay Taiwan!) have closed during the Spring semester, the Brazilian Association of Linguistics, a.k.a. ABRALIN ([Associação Brasileira de Linguística](https://www.abralin.org/site/en/home-page/)), have invited lots of linguists across the world for online lectures that are freely available.
I thought it would be a good idea to document here the ones I have seen, and liked enough to share.
I will categorize them by linguistic subfield and shortly elaborate.

## Lexical Semantics

All linguistic subfields are equal but some are more equal than others.
Lexical semantics is the most equal.

### Dirk Geeraerts - Word meaning research, its scope and development

<iframe width="560" height="315" src="https://www.youtube.com/embed/CzeD4GIfn9s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

>
**Abstract.**
Lexical semantics has changed considerably in the past three decades, not least because of the emergence of Cognitive Semantics. 
To put those changes in the right perspective, this talk will describe the main stages in the development of word meaning research in modern linguistics: from historical semantics in the 19th century, over structuralist semantics in the middle of the 20th century, to neostructuralist and cognitive approaches in the late 20th and early 21st century. 
This evolution will be described from three perspectives: the theoretical one (what are the conflicting or converging assumptions of the approaches?), a descriptive one (what are the phenomena that word meaning research has focused on?), and a methodological one (is there an evolution in the methods of lexical semantics?).


This lecture is largely a copy of one of the basic texts that lexical semanticists should read: Geeraerts, Dirk. 2010. Theories of Lexical Semantics. 
One of Geeraerts's greatest hits is the historical overview of different approaches to lexical semantics in the last 150 years or so. 
Highly recommended if you're interested in this, especially because it becomes more interesting towards the end when he incorporates more recent trends that concern methodological choices that can be made when investigating words.



















